global
    result: float = 0.0;
    buffer: float = 0.0
end

function main():nil
   result = add(2.0, 1.0);
   return nil
end

function add(x: float, y: float):float
        x = x + 2.0;
        local
            i: float = 2.0;
            i = i + 1;
            return 1;
            local
                i: float = 2.0;
                i = i + 1;
                return x + y + i
            end
        end
end